background #0B1020
foreground #C6D8F5

cursor #7EBBE3
cursor_text_color #0B1020

selection_background #5277C3
selection_foreground #FFFFFF

color0  #0B1020
color1  #5277C3
color2  #5C82C8
color3  #668DCD
color4  #7098D2
color5  #79A3D7
color6  #7DAEDD
color7  #B8CBE8

color8  #34415C
color9  #5C82C8
color10 #668DCD
color11 #7098D2
color12 #7EB5E0
color13 #7EB8E2
color14 #7EBBE3
color15 #E5EEFC

# ── Window ──────────────────────────

window_padding_width 12
confirm_os_window_close 0

# ── Cursor ──────────────────────────

cursor_shape block
cursor_blink_interval 0

# ── Tabs ────────────────────────────

tab_bar_edge top
tab_bar_style powerline
active_tab_foreground #0D1117
active_tab_background #82ADFD
inactive_tab_foreground #C6A7FD
inactive_tab_background #1A1F2B

# ── Misc ────────────────────────────

enable_audio_bell no
hide_window_decorations yes
background_opacity 0.8
