theme[main_bg]="#000000"
theme[main_fg]="#F2F2F2"
theme[title]="#FFFFFF"
theme[hi_fg]="#FFFFFF"
theme[selected_bg]="#666666"
theme[selected_fg]="#FFFFFF"
theme[inactive_fg]="#B5B5B5"
theme[proc_misc]="#E0E0E0"

theme[cpu_box]="#666666"
theme[mem_box]="#666666"
theme[net_box]="#666666"
theme[proc_box]="#666666"
theme[div_line]="#666666"

theme[temp_start]="#666666"
theme[temp_mid]="#B5B5B5"
theme[temp_end]="#FFFFFF"

theme[cpu_start]="#666666"
theme[cpu_mid]="#B5B5B5"
theme[cpu_end]="#FFFFFF"

theme[free_start]="#666666"
theme[free_mid]="#B5B5B5"
theme[free_end]="#FFFFFF"

theme[cached_start]="#666666"
theme[cached_mid]="#B5B5B5"
theme[cached_end]="#FFFFFF"

theme[available_start]="#666666"
theme[available_mid]="#B5B5B5"
theme[available_end]="#FFFFFF"

theme[used_start]="#666666"
theme[used_mid]="#B5B5B5"
theme[used_end]="#FFFFFF"

theme[download_start]="#666666"
theme[download_mid]="#B5B5B5"
theme[download_end]="#FFFFFF"

theme[upload_start]="#666666"
theme[upload_mid]="#B5B5B5"
theme[upload_end]="#FFFFFF"

theme[process_start]="#666666"
theme[process_mid]="#B5B5B5"
theme[process_end]="#FFFFFF"
